storage: /boot is now mounted ro
coreos/fedora-coreos-docs pull request #237
Opened 2021-01-15 21:53 UTC by bgilbert

Followup to https://github.com/coreos/fedora-coreos-docs/pull/236#discussion_r558575625.  Hold until https://github.com/coreos/fedora-coreos-config/pull/659 lands in stable.

2021-01-18 10:16 UTC, travier requested changes
LGTM. Can you also update the listing for /boot just above those lines? Thanks!

2021-02-01 15:31 UTC, travier commented
Hold for next stable release.

2021-02-01 15:36 UTC, kelvinfan001 approved these changes
LGTM

2021-02-01 15:46 UTC, travier approved these changes

2021-02-03 18:08 UTC, bgilbert commented
Stable release is out.

2021-02-03 18:11 UTC, bgilbert commented
Rebased; awaiting fixed stable release.

2021-02-03 22:06 UTC, merged